build: false
environment:
  matrix:
    - TOXENV: check
    - TOXENV: "2.7-trollius-mysql
    - TOXENV: "2.7-trollius-mysql-ASPECTLIB_DEBUG=yes
    - TOXENV: "2.7-trollius-mysql-nocover
    - TOXENV: "2.7-trollius-mysql-nocover-ASPECTLIB_DEBUG=yes
    - TOXENV: "3.4
    - TOXENV: "3.4-ASPECTLIB_DEBUG=yes
    - TOXENV: "3.4-nocover
    - TOXENV: "3.4-nocover-ASPECTLIB_DEBUG=yes
init:
  - "ECHO %TOXENV%"
  - ps: "ls C:/Python*"
install:
  - "cd C:/Python27"
  - ps: Invoke-WebRequest "https://bitbucket.org/pypa/setuptools/raw/bootstrap/ez_setup.py" -OutFile "ez_setup.py"
  - ps: Invoke-WebRequest "https://bootstrap.pypa.io/get-pip.py" -OutFile "get-pip.py"
  - python ez_setup.py
  - python get-pip.py
  - "Scripts/pip install tox"
test_script:
  - "c:/python27/Scripts/tox --version"
  - "c:/python27/Scripts/virtualenv --version"
  - "c:/python27/Scripts/pip --version"
  - "c:/python27/Scripts/tox"