build: false
environment:
  matrix:
    - TOXENV: check
{% for env, config in tox_environments|dictsort %}{% if '2.7' in env or '3.4' in env %}
    - TOXENV: "{{ env }}{% if config.cover %},coveralls{% endif %}"
{% endif %}{% endfor %}
init:
  - "ECHO %TOXENV%"
  - ps: "ls C:/Python*"
install:
  - ps: (Invoke-WebRequest "https://bitbucket.org/pypa/setuptools/raw/bootstrap/ez_setup.py").Content | python - tox pip virtualenv
  - ps: (Invoke-WebRequest https://bootstrap.pypa.io/get-pip.py).RawContent | python - tox virtualenv
test_script:
  - "c:/python27/Scripts/tox --version"
  - "c:/python27/Scripts/virtualenv --version"
  - "c:/python27/Scripts/pip --version"
  - "c:/python27/Scripts/tox"