version: '{build}'
build: off
environment:
  matrix:
    - TOXENV: check
      PYTHON_HOME: "C:\\Python27"
      PYTHON_VERSION: "2.7"
      PYTHON_ARCH: "32"
{% for env, config in tox_environments|dictsort %}{% if env.startswith('2.7') or env.startswith('3.4') or env.startswith('3.3') %}
  {% if config['cover'] %}
    - TOXENV: "{{ env }}"
      TOXPYTHON: "C:\\Python{{ env[:3].replace('.', '') }}\\python.exe"
      WINDOWS_SDK_VERSION: "v7.{{ '1' if env[0] == '3' else '0' }}"
      PYTHON_HOME: "C:\\Python{{ env[:3].replace('.', '') }}"
      PYTHON_VERSION: "{{ env[:3] }}"
      PYTHON_ARCH: "32"
  {% endif %}
{% endif %}{% endfor %}
init:
  - "ECHO %TOXENV%"
  - ps: "ls C:\\Python*"
install:
  - "powershell ci\\appveyor-bootstrap.ps1"
test_script:
  - "%PYTHON_HOME%\\Scripts\\tox --version"
  - "%PYTHON_HOME%\\Scripts\\virtualenv --version"
  - "%PYTHON_HOME%\\Scripts\\pip --version"
  - "%PYTHON_HOME%\\Scripts\\tox"
