name: build
on: [push, pull_request]
jobs:
  test:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: 'check'
            python: '3.9'
            toxpython: 'python3.9'
            tox_env: 'check'
            os: 'ubuntu-latest'
          - name: 'docs'
            python: '3.9'
            toxpython: 'python3.9'
            tox_env: 'docs'
            os: 'ubuntu-latest'
          - name: 'py37-cover-release (ubuntu)'
            python: '3.7'
            toxpython: 'python3.7'
            python_arch: 'x64'
            tox_env: 'py37-cover-release,codecov'
            os: 'ubuntu-latest'
          - name: 'py37-cover-debug (ubuntu)'
            python: '3.7'
            toxpython: 'python3.7'
            python_arch: 'x64'
            tox_env: 'py37-cover-debug,codecov'
            os: 'ubuntu-latest'
          - name: 'py37-nocov-release (ubuntu)'
            python: '3.7'
            toxpython: 'python3.7'
            python_arch: 'x64'
            tox_env: 'py37-nocov-release'
            os: 'ubuntu-latest'
          - name: 'py37-nocov-debug (ubuntu)'
            python: '3.7'
            toxpython: 'python3.7'
            python_arch: 'x64'
            tox_env: 'py37-nocov-debug'
            os: 'ubuntu-latest'
          - name: 'py38-cover-release (ubuntu)'
            python: '3.8'
            toxpython: 'python3.8'
            python_arch: 'x64'
            tox_env: 'py38-cover-release,codecov'
            os: 'ubuntu-latest'
          - name: 'py38-cover-debug (ubuntu)'
            python: '3.8'
            toxpython: 'python3.8'
            python_arch: 'x64'
            tox_env: 'py38-cover-debug,codecov'
            os: 'ubuntu-latest'
          - name: 'py38-nocov-release (ubuntu)'
            python: '3.8'
            toxpython: 'python3.8'
            python_arch: 'x64'
            tox_env: 'py38-nocov-release'
            os: 'ubuntu-latest'
          - name: 'py38-nocov-debug (ubuntu)'
            python: '3.8'
            toxpython: 'python3.8'
            python_arch: 'x64'
            tox_env: 'py38-nocov-debug'
            os: 'ubuntu-latest'
          - name: 'py39-cover-release (ubuntu)'
            python: '3.9'
            toxpython: 'python3.9'
            python_arch: 'x64'
            tox_env: 'py39-cover-release,codecov'
            os: 'ubuntu-latest'
          - name: 'py39-cover-debug (ubuntu)'
            python: '3.9'
            toxpython: 'python3.9'
            python_arch: 'x64'
            tox_env: 'py39-cover-debug,codecov'
            os: 'ubuntu-latest'
          - name: 'py39-nocov-release (ubuntu)'
            python: '3.9'
            toxpython: 'python3.9'
            python_arch: 'x64'
            tox_env: 'py39-nocov-release'
            os: 'ubuntu-latest'
          - name: 'py39-nocov-debug (ubuntu)'
            python: '3.9'
            toxpython: 'python3.9'
            python_arch: 'x64'
            tox_env: 'py39-nocov-debug'
            os: 'ubuntu-latest'
          - name: 'py310-cover-release (ubuntu)'
            python: '3.10'
            toxpython: 'python3.10'
            python_arch: 'x64'
            tox_env: 'py310-cover-release,codecov'
            os: 'ubuntu-latest'
          - name: 'py310-cover-debug (ubuntu)'
            python: '3.10'
            toxpython: 'python3.10'
            python_arch: 'x64'
            tox_env: 'py310-cover-debug,codecov'
            os: 'ubuntu-latest'
          - name: 'py310-nocov-release (ubuntu)'
            python: '3.10'
            toxpython: 'python3.10'
            python_arch: 'x64'
            tox_env: 'py310-nocov-release'
            os: 'ubuntu-latest'
          - name: 'py310-nocov-debug (ubuntu)'
            python: '3.10'
            toxpython: 'python3.10'
            python_arch: 'x64'
            tox_env: 'py310-nocov-debug'
            os: 'ubuntu-latest'
          - name: 'pypy37-cover-release (ubuntu)'
            python: 'pypy-3.7'
            toxpython: 'pypy3.7'
            python_arch: 'x64'
            tox_env: 'pypy37-cover-release,codecov'
            os: 'ubuntu-latest'
          - name: 'pypy37-cover-debug (ubuntu)'
            python: 'pypy-3.7'
            toxpython: 'pypy3.7'
            python_arch: 'x64'
            tox_env: 'pypy37-cover-debug,codecov'
            os: 'ubuntu-latest'
          - name: 'pypy37-nocov-release (ubuntu)'
            python: 'pypy-3.7'
            toxpython: 'pypy3.7'
            python_arch: 'x64'
            tox_env: 'pypy37-nocov-release'
            os: 'ubuntu-latest'
          - name: 'pypy37-nocov-debug (ubuntu)'
            python: 'pypy-3.7'
            toxpython: 'pypy3.7'
            python_arch: 'x64'
            tox_env: 'pypy37-nocov-debug'
            os: 'ubuntu-latest'
          - name: 'pypy38-cover-release (ubuntu)'
            python: 'pypy-3.8'
            toxpython: 'pypy3.8'
            python_arch: 'x64'
            tox_env: 'pypy38-cover-release,codecov'
            os: 'ubuntu-latest'
          - name: 'pypy38-cover-debug (ubuntu)'
            python: 'pypy-3.8'
            toxpython: 'pypy3.8'
            python_arch: 'x64'
            tox_env: 'pypy38-cover-debug,codecov'
            os: 'ubuntu-latest'
          - name: 'pypy38-nocov-release (ubuntu)'
            python: 'pypy-3.8'
            toxpython: 'pypy3.8'
            python_arch: 'x64'
            tox_env: 'pypy38-nocov-release'
            os: 'ubuntu-latest'
          - name: 'pypy38-nocov-debug (ubuntu)'
            python: 'pypy-3.8'
            toxpython: 'pypy3.8'
            python_arch: 'x64'
            tox_env: 'pypy38-nocov-debug'
            os: 'ubuntu-latest'
          - name: 'pypy39-cover-release (ubuntu)'
            python: 'pypy-3.9'
            toxpython: 'pypy3.9'
            python_arch: 'x64'
            tox_env: 'pypy39-cover-release,codecov'
            os: 'ubuntu-latest'
          - name: 'pypy39-cover-debug (ubuntu)'
            python: 'pypy-3.9'
            toxpython: 'pypy3.9'
            python_arch: 'x64'
            tox_env: 'pypy39-cover-debug,codecov'
            os: 'ubuntu-latest'
          - name: 'pypy39-nocov-release (ubuntu)'
            python: 'pypy-3.9'
            toxpython: 'pypy3.9'
            python_arch: 'x64'
            tox_env: 'pypy39-nocov-release'
            os: 'ubuntu-latest'
          - name: 'pypy39-nocov-debug (ubuntu)'
            python: 'pypy-3.9'
            toxpython: 'pypy3.9'
            python_arch: 'x64'
            tox_env: 'pypy39-nocov-debug'
            os: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
        architecture: ${{ matrix.python_arch }}
    - name: install dependencies
      run: |
        python -mpip install --progress-bar=off -r ci/requirements.txt
        virtualenv --version
        pip --version
        tox --version
        pip list --format=freeze
    - name: test
      env:
        TOXPYTHON: '${{ matrix.toxpython }}'
      run: >
        tox -e ${{ matrix.tox_env }} -v
